# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will periodically check .NET nanoFramework dependencies and updates them.
# Can also be triggered by a repository dispatch event.

name: Update .NET nanoFramework dependencies

on:
  schedule:
  # At 00:00 UTC every day.
  - cron:  '00 00 * * *'
  repository_dispatch:
    types: update-dependencies

jobs:
  update-dependencies:
    name: nanoFramework
    uses: nanoframework/nf-tools/.github/workflows/update-dependencies.yml@main
    with:
      solutionsToCheck: # Pattern with solution(s) to check.
      workingDirectory: # Working directory to use.
      branchToPr: # Branch to submit PR with updates.
      timeout-minutes: 15 # Timeout for the workflow to complete. Optional.
